const PDFDocument = require("pdfkit");
const Invoice = require("../models/invoice");
const InvoiceLine = require("../models/invoiceline");
const Payment = require("../models/payment");

const generateInvoicePDF = async (req, res) => {
  try {
    const invoiceId = req.params.id;

    const invoice = await Invoice.findById(invoiceId);

    if (!invoice) {
      return res.status(404).json({ message: "Invoice not found" });
    }

    // Security: Only owner can download
    if (invoice.userId.toString() !== req.user._id.toString()) {
      return res.status(403).json({ message: "Access denied" });
    }

    const lineItems = await InvoiceLine.find({ invoiceId });
    const payments = await Payment.find({ invoiceId });

    const subtotal = lineItems.reduce((sum, item) => sum + item.lineTotal, 0);
    const taxPercent = invoice.taxPercent || 0;
    const taxAmount = (subtotal * taxPercent) / 100;
    const total = subtotal + taxAmount;

    const amountPaid = payments.reduce((sum, pay) => sum + pay.amount, 0);
    const balanceDue = total - amountPaid;

    const currencySymbol =
      invoice.currency === "INR"
        ? "₹"
        : invoice.currency === "EUR"
        ? "€"
        : "$";

    // Set PDF headers
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=invoice-${invoice.invoiceNumber}.pdf`
    );

    // Create PDF
    const doc = new PDFDocument({ margin: 50 });

    // Pipe PDF output to response
    doc.pipe(res);

    // ---------------- HEADER ----------------
    doc.fontSize(22).text("Invoice", { align: "center" });
    doc.moveDown(1);

    doc.fontSize(12).text(`Invoice Number: ${invoice.invoiceNumber}`);
    doc.text(`Customer Name: ${invoice.customerName}`);
    doc.text(`Issue Date: ${new Date(invoice.issueDate).toDateString()}`);
    doc.text(`Due Date: ${new Date(invoice.dueDate).toDateString()}`);
    doc.text(`Status: ${invoice.status}`);
    doc.text(`Currency: ${invoice.currency}`);

    doc.moveDown(1.5);

    // ---------------- LINE ITEMS ----------------
    doc.fontSize(16).text("Line Items", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(12);

    lineItems.forEach((item, index) => {
      doc.text(`${index + 1}. ${item.description}`);
      doc.text(`   Quantity: ${item.quantity}`);
      doc.text(`   Unit Price: ${currencySymbol}${item.unitPrice}`);
      doc.text(`   Line Total: ${currencySymbol}${item.lineTotal}`);
      doc.moveDown(0.5);
    });

    doc.moveDown(1);

    // ---------------- TOTALS ----------------
    doc.fontSize(16).text("Totals", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(12).text(`Subtotal: ${currencySymbol}${subtotal.toFixed(2)}`);
    doc.text(
      `Tax (${taxPercent}%): ${currencySymbol}${taxAmount.toFixed(2)}`
    );
    doc.text(`Total: ${currencySymbol}${total.toFixed(2)}`);
    doc.text(`Amount Paid: ${currencySymbol}${amountPaid.toFixed(2)}`);
    doc.text(`Balance Due: ${currencySymbol}${balanceDue.toFixed(2)}`);

    doc.moveDown(1.5);

    // ---------------- PAYMENTS ----------------
    doc.fontSize(16).text("Payments", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(12);

    if (payments.length === 0) {
      doc.text("No payments yet.");
    } else {
      payments.forEach((pay, index) => {
        doc.text(
          `${index + 1}. Paid ${currencySymbol}${pay.amount} on ${new Date(
            pay.paymentDate
          ).toDateString()}`
        );
      });
    }

    doc.moveDown(2);

    // Footer
    doc.fontSize(10).text("Generated by Invoice Management System", {
      align: "center",
      color: "gray",
    });

    // End PDF
    doc.end();
  } catch (error) {
    console.log("PDF Error:", error);
    res.status(500).json({ message: "PDF generation failed" });
  }
};

module.exports = { generateInvoicePDF };
